
// < This file is Auto Generated By EF Core />
using Demo.Abstraction;

namespace Demo.Partial
{
    // Developer 01
    internal partial class Employee : Parent
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int? Age { get; set; }

        // Partial Method
        public partial int DoSomeCode();
        public void Test()
        {
            DoSomeCode();

        }
    }
}
